# Site settings
title: Fran&ccedil;ois Dufeil
email: f.dufeil@yahoo.fr
#># this means to ignore newlines until "baseurl:"
description: Fran&ccedil;ois Dufeil. Fi&egrave;vre obsidionale, Folie obsidionale, Eau + terre + feu = 1:3, Errer dans l'illusion, Spot de replis, O&iuml;kos,  En attendant le feu, Tour interminable, Sort d&eacute;dal&eacute;en,  Les r&eacute;sidus dystopiques, Balise d'urgence, De la d&eacute;flagration de l'emprunt,  Dispositif de mus&eacute;ification, Planter une flaque, Shaquille O'Neal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "francoisdufeil.fr" # the base hostname & protocol for your site
github_username:  Mariecie

# Build settings
# markdown: kramdown
permalink: pretty
#highlighter:      pygments
#highlighter:      rouge

