# Site settings
title: Fran&ccedil;ois Dufeil
email: f.dufeil@yahoo.fr
#># this means to ignore newlines until "baseurl:"
description: Fran&ccedil;ois Dufeil. "Après tout, c’est avec les outils que l’on s’attaque à la restauration. Alors peut-être que leurs griffes, leurs pilons, leurs pressions, leurs combustions serviront un tant soit peu à panser l'animosité architectonique."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "francoisdufeil.fr" # the base hostname & protocol for your site
github_username:  Mariecie

# Build settings
# markdown: kramdown
permalink: pretty
#highlighter:      pygments
#highlighter:      rouge

